import type {
  Organization,
  Project,
  ImpactMetric,
  Evidence,
  Methodology,
  Validator,
  ValidationRequest,
  Certificate,
  Attestation,
} from './types'

// ─── Methodologies ─────────────────────────────────────────────────────────────

export const mockMethodologies: Methodology[] = [
  {
    id: 'meth-001',
    nombre: 'GRI Standards 2021',
    descripcion:
      'Estándar global para la elaboración de memorias de sostenibilidad. Permite a las organizaciones comunicar sus impactos en economía, medio ambiente y personas.',
    version: '2021',
    organizacionEmisora: 'Global Reporting Initiative',
    urlReferencia: 'https://www.globalreporting.org',
    tiposMetrica: ['ambiental', 'social', 'gobernanza'],
    sectores: ['energia_renovable', 'agricultura_regenerativa', 'economia_circular', 'finanzas_impacto'],
    activa: true,
    creadaEn: '2021-10-01',
  },
  {
    id: 'meth-002',
    nombre: 'IRIS+ del GIIN',
    descripcion:
      'Sistema de métricas de impacto del Global Impact Investing Network. Proporciona un lenguaje común para medir, gestionar y optimizar el impacto.',
    version: '5.3',
    organizacionEmisora: 'Global Impact Investing Network',
    urlReferencia: 'https://iris.thegiin.org',
    tiposMetrica: ['social', 'economico', 'ambiental'],
    sectores: ['salud', 'educacion', 'agua_saneamiento', 'finanzas_impacto'],
    activa: true,
    creadaEn: '2019-04-15',
  },
  {
    id: 'meth-003',
    nombre: 'Verificación de Carbono VCS',
    descripcion:
      'Estándar de carbono voluntario que certifica proyectos que reducen o eliminan gases de efecto invernadero.',
    version: '4.5',
    organizacionEmisora: 'Verra',
    urlReferencia: 'https://verra.org/programs/verified-carbon-standard/',
    tiposMetrica: ['ambiental'],
    sectores: ['energia_renovable', 'agricultura_regenerativa'],
    activa: true,
    creadaEn: '2005-11-20',
  },
  {
    id: 'meth-004',
    nombre: 'B Impact Assessment',
    descripcion:
      'Evaluación integral del desempeño social y ambiental de una empresa utilizada para la certificación B Corp.',
    version: '6.0',
    organizacionEmisora: 'B Lab',
    urlReferencia: 'https://www.bcorporation.net',
    tiposMetrica: ['social', 'ambiental', 'gobernanza', 'economico'],
    sectores: ['agricultura_regenerativa', 'economia_circular', 'finanzas_impacto', 'movilidad_sostenible'],
    activa: true,
    creadaEn: '2006-06-01',
  },
]

// ─── Validators ────────────────────────────────────────────────────────────────

export const mockValidators: Validator[] = [
  {
    id: 'val-001',
    nombre: 'Alejandra',
    apellido: 'Torres Mendoza',
    correo: 'a.torres@impactverify.org',
    organizacion: 'ImpactVerify',
    especialidades: ['ambiental', 'social'],
    sectores: ['energia_renovable', 'agricultura_regenerativa'],
    verificacionesRealizadas: 47,
    calificacion: 4.9,
    activo: true,
    avatarUrl: '',
    certificaciones: ['GRI Certified', 'VCS Auditor'],
    ingresadoEn: '2022-03-14',
  },
  {
    id: 'val-002',
    nombre: 'Carlos',
    apellido: 'Reyes Gutiérrez',
    correo: 'c.reyes@impactverify.org',
    organizacion: 'ImpactVerify',
    especialidades: ['economico', 'gobernanza'],
    sectores: ['finanzas_impacto', 'economia_circular'],
    verificacionesRealizadas: 31,
    calificacion: 4.7,
    activo: true,
    avatarUrl: '',
    certificaciones: ['IRIS+ Certified', 'B Impact Assessor'],
    ingresadoEn: '2022-07-01',
  },
  {
    id: 'val-003',
    nombre: 'Sofía',
    apellido: 'Villanueva Ríos',
    correo: 's.villanueva@impactverify.org',
    organizacion: 'ImpactVerify',
    especialidades: ['social', 'ods'],
    sectores: ['educacion', 'salud', 'agua_saneamiento'],
    verificacionesRealizadas: 58,
    calificacion: 4.8,
    activo: true,
    avatarUrl: '',
    certificaciones: ['ODS Expert', 'GIIN Partner'],
    ingresadoEn: '2021-11-20',
  },
]

// ─── Organizations ─────────────────────────────────────────────────────────────

export const mockOrganizations: Organization[] = [
  {
    id: 'org-001',
    slug: 'semilla-solar',
    nombre: 'Semilla Solar',
    descripcion:
      'Empresa social que instala sistemas de energía solar en comunidades rurales de Oaxaca y Chiapas, reduciendo la dependencia de combustibles fósiles y mejorando el acceso a electricidad limpia.',
    sector: 'energia_renovable',
    pais: 'México',
    ciudad: 'Oaxaca de Juárez',
    fundadaEn: '2018-03-15',
    sitioWeb: 'https://semillasolar.mx',
    logoUrl: '',
    coverUrl: '',
    correo: 'contacto@semillasolar.mx',
    verificacionNivel: 'oro',
    verificacionEstado: 'verificado',
    proyectos: 4,
    metricasVerificadas: 18,
    empleados: 34,
    ods: [7, 10, 13, 17],
    etiquetas: ['energía solar', 'comunidades rurales', 'México'],
    creadaEn: '2023-01-10',
    actualizadaEn: '2024-11-05',
  },
  {
    id: 'org-002',
    slug: 'tierra-viva',
    nombre: 'Tierra Viva Cooperativa',
    descripcion:
      'Cooperativa agroecológica que practica agricultura regenerativa en los Andes colombianos, restaurando suelos degradados y fortaleciendo la soberanía alimentaria de pequeños agricultores.',
    sector: 'agricultura_regenerativa',
    pais: 'Colombia',
    ciudad: 'Medellín',
    fundadaEn: '2015-09-01',
    sitioWeb: 'https://tierraviva.co',
    logoUrl: '',
    coverUrl: '',
    correo: 'info@tierraviva.co',
    verificacionNivel: 'platino',
    verificacionEstado: 'verificado',
    proyectos: 6,
    metricasVerificadas: 27,
    empleados: 89,
    ods: [2, 8, 12, 13, 15],
    etiquetas: ['agroecología', 'suelos', 'Colombia', 'cooperativa'],
    creadaEn: '2022-06-20',
    actualizadaEn: '2024-10-18',
  },
  {
    id: 'org-003',
    slug: 'ciclo-urbano',
    nombre: 'Ciclo Urbano',
    descripcion:
      'Startup de economía circular con sede en Buenos Aires que recoge, transforma y redistribuye residuos plásticos postconsumo, generando empleo para personas en situación de vulnerabilidad.',
    sector: 'economia_circular',
    pais: 'Argentina',
    ciudad: 'Buenos Aires',
    fundadaEn: '2019-11-20',
    sitioWeb: 'https://ciclourbano.ar',
    logoUrl: '',
    coverUrl: '',
    correo: 'hola@ciclourbano.ar',
    verificacionNivel: 'plata',
    verificacionEstado: 'verificado',
    proyectos: 3,
    metricasVerificadas: 12,
    empleados: 52,
    ods: [8, 11, 12, 17],
    etiquetas: ['plástico', 'reciclaje', 'Argentina', 'empleo'],
    creadaEn: '2023-04-05',
    actualizadaEn: '2024-09-22',
  },
  {
    id: 'org-004',
    slug: 'agua-clara',
    nombre: 'Agua Clara',
    descripcion:
      'Organización que implementa sistemas de purificación de agua y saneamiento en comunidades indígenas de Guatemala, mejorando la salud y la calidad de vida.',
    sector: 'agua_saneamiento',
    pais: 'Guatemala',
    ciudad: 'Ciudad de Guatemala',
    fundadaEn: '2017-02-10',
    sitioWeb: 'https://aguaclara.gt',
    logoUrl: '',
    coverUrl: '',
    correo: 'contacto@aguaclara.gt',
    verificacionNivel: 'bronce',
    verificacionEstado: 'pendiente',
    proyectos: 2,
    metricasVerificadas: 5,
    empleados: 18,
    ods: [3, 6, 10],
    etiquetas: ['agua potable', 'salud', 'Guatemala', 'pueblos indígenas'],
    creadaEn: '2024-02-12',
    actualizadaEn: '2024-12-01',
  },
]

// ─── Projects ──────────────────────────────────────────────────────────────────

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    slug: 'microrredes-oaxaca',
    organizacionId: 'org-001',
    nombre: 'Microrredes Solares Oaxaca',
    descripcion:
      'Instalación de 12 microrredes solares comunitarias en municipios de difícil acceso en la Sierra Juárez de Oaxaca, beneficiando a más de 2.000 familias.',
    objetivo:
      'Proveer acceso a electricidad limpia y confiable a comunidades rurales sin conexión a la red eléctrica nacional.',
    estado: 'verificado',
    fechaInicio: '2022-01-01',
    fechaFin: null,
    pais: 'México',
    ciudad: 'Sierra Juárez, Oaxaca',
    beneficiarios: 2100,
    ods: [7, 13],
    etiquetas: ['solar', 'microrredes', 'rural'],
    metricasCount: 6,
    evidenciasCount: 14,
    creadoEn: '2022-01-15',
    actualizadoEn: '2024-10-01',
  },
  {
    id: 'proj-002',
    slug: 'restauracion-suelos-andes',
    organizacionId: 'org-002',
    nombre: 'Restauración de Suelos Andinos',
    descripcion:
      'Programa de restauración de 1.200 hectáreas de suelos degradados en el altiplano colombiano mediante técnicas de agroecología y biofertilizantes naturales.',
    objetivo:
      'Recuperar la capacidad productiva y la biodiversidad de suelos erosionados por monocultivos convencionales.',
    estado: 'verificado',
    fechaInicio: '2020-03-01',
    fechaFin: null,
    pais: 'Colombia',
    ciudad: 'Altiplano Cundiboyacense',
    beneficiarios: 340,
    ods: [2, 13, 15],
    etiquetas: ['suelos', 'biodiversidad', 'agroecología'],
    metricasCount: 9,
    evidenciasCount: 23,
    creadoEn: '2020-04-10',
    actualizadoEn: '2024-11-15',
  },
  {
    id: 'proj-003',
    slug: 'planta-reciclaje-ba',
    organizacionId: 'org-003',
    nombre: 'Planta de Reciclaje Inclusivo BA',
    descripcion:
      'Planta de procesamiento de residuos plásticos postconsumo que emplea a 40 personas en situación de vulnerabilidad social en el Gran Buenos Aires.',
    objetivo:
      'Reducir los residuos plásticos en rellenos sanitarios y generar empleo digno para personas vulnerables.',
    estado: 'verificado',
    fechaInicio: '2021-06-01',
    fechaFin: null,
    pais: 'Argentina',
    ciudad: 'Gran Buenos Aires',
    beneficiarios: 40,
    ods: [8, 12],
    etiquetas: ['plástico', 'reciclaje', 'empleo inclusivo'],
    metricasCount: 5,
    evidenciasCount: 10,
    creadoEn: '2021-07-01',
    actualizadoEn: '2024-09-30',
  },
  {
    id: 'proj-004',
    slug: 'agua-potable-quiche',
    organizacionId: 'org-004',
    nombre: 'Agua Potable para el Quiché',
    descripcion:
      'Instalación de sistemas de purificación y distribución de agua potable en 8 comunidades indígenas del departamento del Quiché, Guatemala.',
    objetivo:
      'Garantizar acceso sostenible a agua potable y reducir enfermedades de transmisión hídrica.',
    estado: 'pendiente',
    fechaInicio: '2023-09-01',
    fechaFin: '2025-08-31',
    pais: 'Guatemala',
    ciudad: 'Quiché',
    beneficiarios: 4500,
    ods: [3, 6],
    etiquetas: ['agua potable', 'salud comunitaria'],
    metricasCount: 3,
    evidenciasCount: 4,
    creadoEn: '2023-09-15',
    actualizadoEn: '2024-11-20',
  },
]

// ─── ImpactMetrics ─────────────────────────────────────────────────────────────

export const mockMetrics: ImpactMetric[] = [
  {
    id: 'met-001',
    proyectoId: 'proj-001',
    organizacionId: 'org-001',
    nombre: 'Capacidad instalada de generación solar',
    descripcion: 'Megavatios pico (MWp) de energía solar instalados en las comunidades del proyecto.',
    tipo: 'ambiental',
    unidad: 'MWp',
    valorLinea: 0,
    valorActual: 1.8,
    valorMeta: 2.4,
    periodo: '2024-Q3',
    estado: 'verificado',
    metodologiaId: 'meth-003',
    evidenciasCount: 3,
    ods: [7],
    creadaEn: '2022-02-01',
    verificadaEn: '2024-09-15',
  },
  {
    id: 'met-002',
    proyectoId: 'proj-001',
    organizacionId: 'org-001',
    nombre: 'Toneladas de CO₂ evitadas',
    descripcion:
      'Emisiones de CO₂ equivalente evitadas al desplazar el uso de generadores diésel por energía solar.',
    tipo: 'ambiental',
    unidad: 'tCO₂e/año',
    valorLinea: 0,
    valorActual: 2340,
    valorMeta: 3200,
    periodo: '2024-Q3',
    estado: 'verificado',
    metodologiaId: 'meth-003',
    evidenciasCount: 4,
    ods: [13],
    creadaEn: '2022-02-01',
    verificadaEn: '2024-09-15',
  },
  {
    id: 'met-003',
    proyectoId: 'proj-002',
    organizacionId: 'org-002',
    nombre: 'Hectáreas de suelo restaurado',
    descripcion: 'Superficie de suelo degradado recuperada mediante prácticas agroecológicas.',
    tipo: 'ambiental',
    unidad: 'ha',
    valorLinea: 0,
    valorActual: 876,
    valorMeta: 1200,
    periodo: '2024-Q4',
    estado: 'verificado',
    metodologiaId: 'meth-004',
    evidenciasCount: 6,
    ods: [15],
    creadaEn: '2020-04-15',
    verificadaEn: '2024-11-10',
  },
  {
    id: 'met-004',
    proyectoId: 'proj-002',
    organizacionId: 'org-002',
    nombre: 'Agricultores capacitados en agroecología',
    descripcion:
      'Número de agricultores que completaron el programa de formación en prácticas regenerativas.',
    tipo: 'social',
    unidad: 'personas',
    valorLinea: 0,
    valorActual: 312,
    valorMeta: 400,
    periodo: '2024-Q4',
    estado: 'verificado',
    metodologiaId: 'meth-002',
    evidenciasCount: 5,
    ods: [2, 8],
    creadaEn: '2020-04-15',
    verificadaEn: '2024-11-10',
  },
  {
    id: 'met-005',
    proyectoId: 'proj-003',
    organizacionId: 'org-003',
    nombre: 'Toneladas de plástico reciclado',
    descripcion: 'Peso total de residuos plásticos procesados y reintroducidos al ciclo productivo.',
    tipo: 'ambiental',
    unidad: 'toneladas/mes',
    valorLinea: 0,
    valorActual: 48,
    valorMeta: 80,
    periodo: '2024-Q3',
    estado: 'verificado',
    metodologiaId: 'meth-001',
    evidenciasCount: 4,
    ods: [12],
    creadaEn: '2021-07-15',
    verificadaEn: '2024-09-01',
  },
  {
    id: 'met-006',
    proyectoId: 'proj-003',
    organizacionId: 'org-003',
    nombre: 'Empleos dignos generados',
    descripcion:
      'Puestos de trabajo con salario justo, seguridad social y condiciones laborales dignas para personas vulnerables.',
    tipo: 'social',
    unidad: 'empleos',
    valorLinea: 0,
    valorActual: 40,
    valorMeta: 60,
    periodo: '2024-Q3',
    estado: 'verificado',
    metodologiaId: 'meth-002',
    evidenciasCount: 3,
    ods: [8],
    creadaEn: '2021-07-15',
    verificadaEn: '2024-09-01',
  },
  {
    id: 'met-007',
    proyectoId: 'proj-004',
    organizacionId: 'org-004',
    nombre: 'Personas con acceso a agua potable',
    descripcion: 'Número de personas que obtuvieron acceso a agua potable segura gracias al proyecto.',
    tipo: 'social',
    unidad: 'personas',
    valorLinea: 0,
    valorActual: 2800,
    valorMeta: 4500,
    periodo: '2024-Q4',
    estado: 'pendiente',
    metodologiaId: 'meth-002',
    evidenciasCount: 2,
    ods: [6],
    creadaEn: '2023-10-01',
    verificadaEn: null,
  },
]

// ─── Evidences ─────────────────────────────────────────────────────────────────

export const mockEvidences: Evidence[] = [
  {
    id: 'ev-001',
    metricaId: 'met-001',
    proyectoId: 'proj-001',
    tipo: 'informe',
    titulo: 'Informe de Instalación — Fase 1',
    descripcion: 'Informe técnico con especificaciones de los sistemas instalados en 6 comunidades.',
    archivoUrl: '#',
    archivoNombre: 'informe_instalacion_fase1.pdf',
    archivoTamanio: 4200000,
    estado: 'verificado',
    subidaEn: '2023-06-15',
    verificadaEn: '2023-07-20',
    verificadorId: 'val-001',
    notas: 'Documentación completa y datos de factura técnica revisados.',
  },
  {
    id: 'ev-002',
    metricaId: 'met-002',
    proyectoId: 'proj-001',
    tipo: 'datos_sensor',
    titulo: 'Datos de generación solar — Q3 2024',
    descripcion: 'Exportación de datos de los medidores inteligentes instalados en las microrredes.',
    archivoUrl: '#',
    archivoNombre: 'sensor_data_q3_2024.csv',
    archivoTamanio: 890000,
    estado: 'verificado',
    subidaEn: '2024-10-01',
    verificadaEn: '2024-10-18',
    verificadorId: 'val-001',
    notas: 'Datos consistentes con lecturas anteriores. Sin anomalías detectadas.',
  },
  {
    id: 'ev-003',
    metricaId: 'met-003',
    proyectoId: 'proj-002',
    tipo: 'auditoria',
    titulo: 'Auditoría de suelos — Laboratorio UdeA',
    descripcion:
      'Resultados de análisis de laboratorio de muestras de suelo tomadas en las parcelas restauradas.',
    archivoUrl: '#',
    archivoNombre: 'auditoria_suelos_2024.pdf',
    archivoTamanio: 6100000,
    estado: 'verificado',
    subidaEn: '2024-08-20',
    verificadaEn: '2024-09-10',
    verificadorId: 'val-001',
    notas: 'Los resultados confirman mejora significativa en contenido de materia orgánica.',
  },
  {
    id: 'ev-004',
    metricaId: 'met-007',
    proyectoId: 'proj-004',
    tipo: 'fotografia',
    titulo: 'Registro fotográfico — Instalaciones Quiché',
    descripcion: 'Registro fotográfico de los sistemas instalados en las primeras 3 comunidades.',
    archivoUrl: '#',
    archivoNombre: 'fotos_quiche_oct2024.zip',
    archivoTamanio: 28000000,
    estado: 'pendiente',
    subidaEn: '2024-10-25',
    verificadaEn: null,
    verificadorId: null,
    notas: '',
  },
]

// ─── ValidationRequests ────────────────────────────────────────────────────────

export const mockValidationRequests: ValidationRequest[] = [
  {
    id: 'vr-001',
    proyectoId: 'proj-001',
    organizacionId: 'org-001',
    validadorId: 'val-001',
    tipo: 'proyecto',
    referenciaId: 'proj-001',
    estado: 'verificado',
    nivelSolicitado: 'oro',
    descripcion: 'Solicitud de verificación nivel Oro para el proyecto Microrredes Solares Oaxaca.',
    comentarios:
      'Toda la documentación ha sido revisada. Los datos de generación están respaldados por medidores calibrados.',
    prioridad: 'alta',
    fechaSolicitud: '2024-07-01',
    fechaLimite: '2024-09-30',
    fechaResolucion: '2024-09-15',
    historial: [
      {
        id: 'rev-001',
        solicitudId: 'vr-001',
        autorId: 'admin-001',
        autorNombre: 'Semilla Solar',
        autorRol: 'administrador_empresa',
        tipo: 'cambio_estado',
        contenido: 'Solicitud de verificación enviada.',
        estadoAnterior: 'borrador',
        estadoNuevo: 'pendiente',
        creadoEn: '2024-07-01T10:00:00Z',
      },
      {
        id: 'rev-002',
        solicitudId: 'vr-001',
        autorId: 'val-001',
        autorNombre: 'Alejandra Torres Mendoza',
        autorRol: 'validador',
        tipo: 'cambio_estado',
        contenido: 'Solicitud asignada. Inicio de revisión documental.',
        estadoAnterior: 'pendiente',
        estadoNuevo: 'en_revision',
        creadoEn: '2024-07-15T09:00:00Z',
      },
      {
        id: 'rev-003',
        solicitudId: 'vr-001',
        autorId: 'val-001',
        autorNombre: 'Alejandra Torres Mendoza',
        autorRol: 'validador',
        tipo: 'solicitud_evidencia',
        contenido: 'Se requiere informe de impacto comunitario firmado por el ayuntamiento.',
        estadoAnterior: null,
        estadoNuevo: null,
        creadoEn: '2024-08-05T14:30:00Z',
      },
      {
        id: 'rev-004',
        solicitudId: 'vr-001',
        autorId: 'val-001',
        autorNombre: 'Alejandra Torres Mendoza',
        autorRol: 'validador',
        tipo: 'aprobacion',
        contenido:
          'Verificación completada. Toda la evidencia es sólida y la metodología está bien aplicada. Se recomienda la certificación Oro.',
        estadoAnterior: 'en_revision',
        estadoNuevo: 'verificado',
        creadoEn: '2024-09-15T11:00:00Z',
      },
    ],
  },
  {
    id: 'vr-002',
    proyectoId: 'proj-004',
    organizacionId: 'org-004',
    validadorId: 'val-003',
    tipo: 'proyecto',
    referenciaId: 'proj-004',
    estado: 'en_revision',
    nivelSolicitado: 'bronce',
    descripcion: 'Primera solicitud de verificación para el proyecto Agua Potable para el Quiché.',
    comentarios: '',
    prioridad: 'media',
    fechaSolicitud: '2024-11-01',
    fechaLimite: '2025-01-31',
    fechaResolucion: null,
    historial: [
      {
        id: 'rev-005',
        solicitudId: 'vr-002',
        autorId: 'admin-004',
        autorNombre: 'Agua Clara',
        autorRol: 'administrador_empresa',
        tipo: 'cambio_estado',
        contenido: 'Primera solicitud de verificación enviada.',
        estadoAnterior: 'borrador',
        estadoNuevo: 'pendiente',
        creadoEn: '2024-11-01T08:00:00Z',
      },
      {
        id: 'rev-006',
        solicitudId: 'vr-002',
        autorId: 'val-003',
        autorNombre: 'Sofía Villanueva Ríos',
        autorRol: 'validador',
        tipo: 'cambio_estado',
        contenido: 'Solicitud aceptada. Revisando la documentación del proyecto.',
        estadoAnterior: 'pendiente',
        estadoNuevo: 'en_revision',
        creadoEn: '2024-11-15T10:00:00Z',
      },
    ],
  },
  {
    id: 'vr-003',
    proyectoId: 'proj-002',
    organizacionId: 'org-002',
    validadorId: null,
    tipo: 'metrica',
    referenciaId: 'met-003',
    estado: 'pendiente',
    nivelSolicitado: 'platino',
    descripcion: 'Solicitud de reverificación anual de la métrica de hectáreas restauradas.',
    comentarios: '',
    prioridad: 'alta',
    fechaSolicitud: '2024-12-01',
    fechaLimite: '2025-01-15',
    fechaResolucion: null,
    historial: [
      {
        id: 'rev-007',
        solicitudId: 'vr-003',
        autorId: 'admin-002',
        autorNombre: 'Tierra Viva Cooperativa',
        autorRol: 'administrador_empresa',
        tipo: 'cambio_estado',
        contenido: 'Solicitud de reverificación enviada con nuevos datos de campo.',
        estadoAnterior: 'borrador',
        estadoNuevo: 'pendiente',
        creadoEn: '2024-12-01T09:00:00Z',
      },
    ],
  },
]

// ─── Certificates ──────────────────────────────────────────────────────────────

export const mockCertificates: Certificate[] = [
  {
    id: 'cert-001',
    numero: 'IV-2024-0018',
    organizacionId: 'org-001',
    proyectoId: 'proj-001',
    nivel: 'oro',
    estado: 'activo',
    emitidoEn: '2024-09-20',
    expiraEn: '2026-09-20',
    emisorNombre: 'Alejandra Torres Mendoza',
    emisorId: 'val-001',
    metricasIncluidas: ['met-001', 'met-002'],
    urlPublica: '/verify?cert=IV-2024-0018',
    codigoVerificacion: 'SSOL-ORO-2024-A8X2',
  },
  {
    id: 'cert-002',
    numero: 'IV-2023-0007',
    organizacionId: 'org-002',
    proyectoId: 'proj-002',
    nivel: 'platino',
    estado: 'activo',
    emitidoEn: '2023-12-01',
    expiraEn: '2025-12-01',
    emisorNombre: 'Alejandra Torres Mendoza',
    emisorId: 'val-001',
    metricasIncluidas: ['met-003', 'met-004'],
    urlPublica: '/verify?cert=IV-2023-0007',
    codigoVerificacion: 'TVCO-PLAT-2023-K5R9',
  },
  {
    id: 'cert-003',
    numero: 'IV-2024-0031',
    organizacionId: 'org-003',
    proyectoId: 'proj-003',
    nivel: 'plata',
    estado: 'activo',
    emitidoEn: '2024-09-05',
    expiraEn: '2026-09-05',
    emisorNombre: 'Carlos Reyes Gutiérrez',
    emisorId: 'val-002',
    metricasIncluidas: ['met-005', 'met-006'],
    urlPublica: '/verify?cert=IV-2024-0031',
    codigoVerificacion: 'CURB-PLAT-2024-M3Q7',
  },
]

// ─── Attestations ──────────────────────────────────────────────────────────────

export const mockAttestations: Attestation[] = [
  {
    id: 'att-001',
    certificadoId: 'cert-001',
    validadorId: 'val-001',
    metricaId: 'met-001',
    valor: 1.8,
    unidad: 'MWp',
    periodoInicio: '2022-01-01',
    periodoFin: '2024-09-15',
    metodologiaId: 'meth-003',
    notas: 'Valor confirmado por datos de instalación y medición en campo.',
    firmadaEn: '2024-09-15T11:05:00Z',
    valida: true,
  },
  {
    id: 'att-002',
    certificadoId: 'cert-002',
    validadorId: 'val-001',
    metricaId: 'met-003',
    valor: 876,
    unidad: 'ha',
    periodoInicio: '2020-03-01',
    periodoFin: '2024-11-10',
    metodologiaId: 'meth-004',
    notas: 'Análisis de suelos y verificación satelital confirman el área restaurada.',
    firmadaEn: '2024-11-10T15:30:00Z',
    valida: true,
  },
]

// ─── Mock Service Adapters ──────────────────────────────────────────────────────
// These adapters act as the integration boundary. Replace with real API calls
// without changing the component layer.

export const organizacionesService = {
  getAll: (): Promise<Organization[]> => Promise.resolve(mockOrganizations),
  getBySlug: (slug: string): Promise<Organization | undefined> =>
    Promise.resolve(mockOrganizations.find((o) => o.slug === slug)),
  getById: (id: string): Promise<Organization | undefined> =>
    Promise.resolve(mockOrganizations.find((o) => o.id === id)),
}

export const proyectosService = {
  getAll: (): Promise<Project[]> => Promise.resolve(mockProjects),
  getByOrg: (orgId: string): Promise<Project[]> =>
    Promise.resolve(mockProjects.filter((p) => p.organizacionId === orgId)),
  getById: (id: string): Promise<Project | undefined> =>
    Promise.resolve(mockProjects.find((p) => p.id === id)),
}

export const metricasService = {
  getAll: (): Promise<ImpactMetric[]> => Promise.resolve(mockMetrics),
  getByProject: (projId: string): Promise<ImpactMetric[]> =>
    Promise.resolve(mockMetrics.filter((m) => m.proyectoId === projId)),
}

export const solicitudesService = {
  getAll: (): Promise<ValidationRequest[]> => Promise.resolve(mockValidationRequests),
  getPending: (): Promise<ValidationRequest[]> =>
    Promise.resolve(
      mockValidationRequests.filter((r) => r.estado === 'pendiente' || r.estado === 'en_revision'),
    ),
  getByOrg: (orgId: string): Promise<ValidationRequest[]> =>
    Promise.resolve(mockValidationRequests.filter((r) => r.organizacionId === orgId)),
}

export const certificadosService = {
  getAll: (): Promise<Certificate[]> => Promise.resolve(mockCertificates),
  getByOrg: (orgId: string): Promise<Certificate[]> =>
    Promise.resolve(mockCertificates.filter((c) => c.organizacionId === orgId)),
  getByCode: (code: string): Promise<Certificate | undefined> =>
    Promise.resolve(mockCertificates.find((c) => c.codigoVerificacion === code || c.numero === code)),
}

export const validadoresService = {
  getAll: (): Promise<Validator[]> => Promise.resolve(mockValidators),
  getById: (id: string): Promise<Validator | undefined> =>
    Promise.resolve(mockValidators.find((v) => v.id === id)),
}

export const metodologiasService = {
  getAll: (): Promise<Methodology[]> => Promise.resolve(mockMethodologies),
  getById: (id: string): Promise<Methodology | undefined> =>
    Promise.resolve(mockMethodologies.find((m) => m.id === id)),
}
